config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'
  get 'resumes/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :resumes,only:[:index,:new,:create,:destroy]
root 'resumes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
	mount_uploader:attachment,AttachmentUploader
	validates :name,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
  	@resumes=Resume.all
  end

  def new
  	binding.pry
  	@resume=Resume.new
  end

  def create
  	@resume= Resume.new(resume_params)
  	 if @resume.save
  	 	redirect_to resumes_index_path, notice:"Successfully uploaded"
  	 else 
  	 	binding.pry
  	 	render new
  	 end

  end

  def destroy
  	@resume = Resume.find(params[:id]) 
  	@resume.destroy
  	redirect_to resumes_path, notice: "Successfully Deleted"
  end
  private
  def resume_params
  	params.require(:resume).permit(:name,:attachment)
  end
end
#send_file '/path/to/file', :type => 'image/jpeg', :disposition => 'attachment'

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Upload</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<div class="container">
<% if !flash[:notice].blank? %>
<div>
	<%= flash[:notice] %>
</div>                    
<% end %>
<br>
<%= link_to "New Resume",resumes_new_path %>
<br>
<br>
<table border="3">
	<thread>
	<tr>
	<th>Candiate Name</th>
	<th>Download Link</th>
	<th> Action</th>
</tr>
</thread>
<tbody>
	<% @resumes.each do |resume| %>
	<tr>
		<td><%= resume.name %></td>
		<td><%= link_to "Download", resume.attachment_url %></td>
		<td><%= link_to "Delete", resume,method: :delete%></td>
	</tr>
	<% end %>	
</tbody>
</table>
</div>

app/views/resumes/new.html.erb
<div class="container">
	<% if !@resume.errors.empty? %>
<div>
	<ul>
	<% @resume.errors.full_messages.each do|msg|%>
	<li><%= msg %></li>
<% end %></ul>
</div>
<% end %>
	<div class="container">
	<% if !@resume.errors.empty? %>
<div>
	<ul>
	<% @resume.errors.full_messages.each do|msg|%>
	<li><%= msg %></li>
<%end %></ul>
</div>
<% end %>
<div>   
   <%= form_for @resume, html: { multipart: true } do |f| %>   
      <%= f.label :name %>   
      <%= f.text_field :name %>   
      <br><br>   
      <%= f.label :attachment %>   
      <%= f.file_field :attachment %>   
      <br>   
      <%= f.submit "Save" %>   
   <% end %>   
</div>   
</div>  
</div>